package AimLabs;
import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import java.util.TimerTask;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bened
 */
public class AimLabs extends javax.swing.JFrame {

    /**
     * Creates new form AimLabs
     */
    
    public AimLabs() {
        initComponents();
    }
    //moving object
    Random rand = new Random(); 
    int x,y;
    int count=0;
    double pressed,percent;
    int low = 70;
    int high = 380;
    int xlow = 20;
    int xhigh = 700;
    //timer
    private final static int DELAY = 1000;
    private final static int PERIOD = 1000;
    java.util.Timer timer;
    boolean startBool=false;
    int num=10;
    

    //timer
    public void go(){
        TimerTask task = new MyTimerTask2(this);
        timer = new java.util.Timer();
        timer.schedule(task,DELAY,PERIOD);
        
    }
    
    // target moving
    private void moveObj(){ 
        int upperbound = 500;
        x = rand.nextInt(xhigh-xlow) + xlow;
        y = rand.nextInt(high-low) + low;

        this.remove(jLabel1);
        this.revalidate();
        this.repaint();
        jLabel1.setLocation(x, y);
        this.add(jPanel1);
        
    }
    public int counterScore()
    {
    return count;
    }
    
    //display timer
    public void disp(){
        if (num==10){
            jTextField2.setForeground(Color.yellow);
        }
        if(num==5){
            jTextField2.setForeground(Color.red);
        }
        if(num == 0) {
            jTextField2.setForeground(Color.yellow);      
            jLabel1.setVisible(false);
            jPlay.setEnabled(true);
            timer.cancel();                                                             // To stop timer
        }
        jTextField2.setText("TIMER: "+num);
        
    }
    
    //Function for sound
    private void sound(){
        try {
            File sound = new File("src\\Music\\pop.wav");                               //change directory
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(sound);
            Clip c = AudioSystem.getClip();
            c.open(audioStream);                                                        // opens the file
            c.start();                                                                  // To play the sound
        }
        catch(Exception e){
        }
    }
    public void dataTrans() throws IOException{
        FileWriter fw= new FileWriter("data.txt");
        percent = count/pressed;
        percent = Math.round(percent * 100.0) / 100.0;
        fw.write(count+"\n");
        fw.write(percent+"\n");
        fw.close();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scoreBoard = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        Play = new javax.swing.JMenu();
        jPlay = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 0, 102));
        setMaximumSize(new java.awt.Dimension(805, 505));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(805, 505));
        setSize(new java.awt.Dimension(805, 505));

        jPanel1.setBackground(new java.awt.Color(25, 25, 73));
        jPanel1.setMaximumSize(new java.awt.Dimension(805, 505));
        jPanel1.setMinimumSize(new java.awt.Dimension(805, 505));
        jPanel1.setPreferredSize(new java.awt.Dimension(805, 505));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scoreBoard.setEditable(false);
        scoreBoard.setBackground(new java.awt.Color(25, 25, 73));
        scoreBoard.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        scoreBoard.setForeground(new java.awt.Color(255, 255, 0));
        scoreBoard.setText("SCORE:");
        scoreBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreBoardActionPerformed(evt);
            }
        });
        jPanel1.add(scoreBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 121, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(25, 25, 73));
        jTextField2.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 0));
        jTextField2.setText("TIME:");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 121, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Target.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 225, 78, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AimLabs/bg2.gif"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 510));

        Play.setText("Start");
        Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });

        jPlay.setText("Play");
        jPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });
        Play.add(jPlay);

        jMenuBar2.add(Play);

        jMenu2.setText("Quit");

        jExit.setText("Exit Game");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        jMenu2.add(jExit);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        count++;
        pressed++;
        scoreBoard.setText("SCORE: " + count);
        moveObj();
        sound();
    }//GEN-LAST:event_jPanel2MousePressed

    private void PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayActionPerformed
        // TODO add your handling code here:
        Object obj = evt.getSource();
        
        if(obj == jPlay) {
            
            num=20;
            count=0;
            pressed=0;
            scoreBoard.setText("SCORE: 0");
            go(); 
            
            if(num == 20)
                jLabel1.setVisible(true);
                jPlay.setEnabled(false);

        }
    }//GEN-LAST:event_PlayActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        // TODO add your handling code here:
        Object obj = evt.getSource();
        
        if(obj == jExit)
            System.exit(0);
    }//GEN-LAST:event_jExitActionPerformed

    private void scoreBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreBoardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreBoardActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        pressed++;
        moveObj();
    }//GEN-LAST:event_jLabel2MouseClicked
   

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AimLabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AimLabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AimLabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AimLabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AimLabs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Play;
    private javax.swing.JMenuItem jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jPlay;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField scoreBoard;
    // End of variables declaration//GEN-END:variables

  
}
